apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 001-agentgateway.yaml
  - 002-agentregistry.yaml
  - 003-kagent.yaml
  - 004-phoenix.yaml
  - 005-qdrant.yaml
  - 006-agent-retrieval.yaml
  - 007-llama-cpp-embeddings.yaml
  - 008-llmd.yaml
  - 009-mcp-servers.yaml
  - 010-neo4j.yaml
